name: Flutter Apk Build On Push

on: [push, workflow_dispatch]

concurrency:
  group: apk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apkbuild:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Download Firebase Config
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: 'google-services.json'
          json: ${{ secrets.FIREBASE_CONFIG }}
          dir: 'android/app/'

      - name: Build Android Apk Release
        run: flutter build apk --release

      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: build/app/outputs/flutter-apk/app-release.apk
